### ISSUE TITLE
New training ideas raised during the CWG meeting

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#162]
@VirginieCorraze (pending invitation) suggested additional training during the [Community WG call today](https://github.com/Green-Software-Foundation/community-wg/issues/48). 
Discussion to be continued in this repo.
@greenhsu123 @tmcclell

**Comment by VirginieCorraze** [comment]
It would be great to have an e-certification related covering the patterns addressing the early phases of the solutions design:
•	GREEN BY DESIGN: eco-design practices to adopt at the early stages of the product design (scoping phase, high-level requirements, mock-up)  

•	Targeted audience: Product Owner, Product manager, Business analyst

•	How to manage the design and delivery of IT solutions by minimizing environmental impact 
•	The right questions to consider, how to arbitrate
•	How to determine the arguments to embark the internal stakeholders and customers on a responsible aproach.
•	How to make trade-offs according to your priorities
•	Define the key performance indicators and measurement to achieve your goals
•	Role and responsibly of the Product Owner

**Comment by jawache** [comment]
@holanita is there some way to convert this to a discussion? Used to be a button to flip between the two but can't find it. This is an open ended discussion I would say.

**Comment by benhamidene** [comment]
> @holanita @jawache following our discussion at the community workgroup yesterday: It would be very valuable to have an e-certification covering the early phases of the solutions design, to take the right decisions and influence from the very beginning: • GREEN BY DESIGN: eco-design practices to adopt at the early stages of the product design (scoping phase, high-level requirements, mock-up)
> 
> • Targeted audience: Product Owner, Product manager, Business analyst
> 
> • How to manage the design and delivery of IT solutions by minimizing environmental impact • The right questions to consider, how to arbitrate • How to determine the arguments to embark the internal stakeholders and customers on a responsible aproach. • How to make trade-offs according to your priorities • Define the key performance indicators and measurement to achieve your goals • Role and responsibly of the Product Owner

I support and welcome this suggestion and propose to help on this topic
